### ISSUE TITLE
compiling errors in sudoku-Generator file

### ISSUE THREAD

**Issue by kartikey-codes** [ArjArav98/Sudoku-Solver#11]
![issues](https://user-images.githubusercontent.com/96256984/196811775-d1dad4f8-4c0d-4201-816d-87a6c8132303.png)

**Comment by kartikey-codes** [comment]
please assign this issue to me :)

**Comment by ArjArav98** [comment]
Hi @kartikey-codes, apologies for the delay, I just saw this.
Are you interested in raising a PR for this issue?

**Comment by ArjArav98** [comment]
Hi @kartikey-codes, the repository underwent a rewrite. Please let me know if the issue you faced has been fixed.
