### ISSUE TITLE
Wrong solution for random input numbers without validation 

### ISSUE THREAD

**Issue by Puneetpotter** [ArjArav98/Sudoku-Solver#12]
After compilation, the sudoku solver **should be able to first identify** if the input numbers can form correct solution or not. I just gave input of random numbers, still I got a solution which is **absolutely wrong**. From the image [attached]((https://user-images.githubusercontent.com/73062696/200591902-ba0c32a2-3b5b-4750-bddd-4ac69965b7ae.png)) we can see how same digits are repeated in a square as well as horizontally and vertically, which contradicts the property of sudoku. 

![Screenshot sudoku solver](https://user-images.githubusercontent.com/73062696/200591902-ba0c32a2-3b5b-4750-bddd-4ac69965b7ae.png)

**Comment by ArjArav98** [comment]
Hi @Puneetpotter, thanks for submitting this issue!
Hmm, this is definitely an interesting problem. You're right, it's supposed to validate the question before it can solve it.
I'll add in a fix for this.

**Comment by ArjArav98** [comment]
Hi @Puneetpotter, the repository underwent a rewrite. Let me know if the particular bug you faced has been fixed.
